/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingArticlesRouteImport } from './routes/_marketing/articles'
import { Route as MarketingChromeExtensionRouteImport } from './routes/_marketing/chrome-extension'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingIosAppRouteImport } from './routes/_marketing/ios-app'
import { Route as MarketingPocketAlternativeRouteImport } from './routes/_marketing/pocket-alternative'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingRaycastRouteImport } from './routes/_marketing/raycast'
import { Route as MarketingSafariBookmarkManagerRouteImport } from './routes/_marketing/safari-bookmark-manager'
import { Route as MarketingSupportRouteImport } from './routes/_marketing/support'
import { Route as MarketingWebCompanionRouteImport } from './routes/_marketing/web-companion'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as OauthLoginRouteImport } from './routes/oauth/login'
import { Route as MarketingArticlesBestBookmarkManagerChromeRouteImport } from './routes/_marketing/articles_.best-bookmark-manager-chrome'
import { Route as MarketingArticlesBestReadItLaterAppsRouteImport } from './routes/_marketing/articles_.best-read-it-later-apps'
import { Route as MarketingArticlesBookmarkManagerForDevelopersRouteImport } from './routes/_marketing/articles_.bookmark-manager-for-developers'
import { Route as MarketingArticlesChromeBookmarksBarRouteImport } from './routes/_marketing/articles_.chrome-bookmarks-bar'
import { Route as MarketingArticlesExportImportBookmarksRouteImport } from './routes/_marketing/articles_.export-import-bookmarks'
import { Route as MarketingArticlesHowToOrganizeBookmarksChromeRouteImport } from './routes/_marketing/articles_.how-to-organize-bookmarks-chrome'
import { Route as MarketingArticlesHowToOrganizeTooManyOpenTabsRouteImport } from './routes/_marketing/articles_.how-to-organize-too-many-open-tabs'
import { Route as MarketingArticlesReadLaterAppChromeIphoneRouteImport } from './routes/_marketing/articles_.read-later-app-chrome-iphone'
import { Route as MarketingArticlesSafariReadingListRouteImport } from './routes/_marketing/articles_.safari-reading-list'
import { Route as MarketingArticlesSaveLinksWithRaycastRouteImport } from './routes/_marketing/articles_.save-links-with-raycast'
import { Route as MarketingArticlesWhereAreMyBookmarksRouteImport } from './routes/_marketing/articles_.where-are-my-bookmarks'
import { Route as MarketingUHandleRouteImport } from './routes/_marketing/u.$handle'
import { Route as AppLibraryFoldersFolderIdRouteImport } from './routes/_app/library_.folders.$folderId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingArticlesRoute = MarketingArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChromeExtensionRoute =
  MarketingChromeExtensionRouteImport.update({
    id: '/chrome-extension',
    path: '/chrome-extension',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIosAppRoute = MarketingIosAppRouteImport.update({
  id: '/ios-app',
  path: '/ios-app',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPocketAlternativeRoute =
  MarketingPocketAlternativeRouteImport.update({
    id: '/pocket-alternative',
    path: '/pocket-alternative',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRaycastRoute = MarketingRaycastRouteImport.update({
  id: '/raycast',
  path: '/raycast',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSafariBookmarkManagerRoute =
  MarketingSafariBookmarkManagerRouteImport.update({
    id: '/safari-bookmark-manager',
    path: '/safari-bookmark-manager',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingSupportRoute = MarketingSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingWebCompanionRoute = MarketingWebCompanionRouteImport.update({
  id: '/web-companion',
  path: '/web-companion',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingArticlesBestBookmarkManagerChromeRoute =
  MarketingArticlesBestBookmarkManagerChromeRouteImport.update({
    id: '/articles_/best-bookmark-manager-chrome',
    path: '/articles/best-bookmark-manager-chrome',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesBestReadItLaterAppsRoute =
  MarketingArticlesBestReadItLaterAppsRouteImport.update({
    id: '/articles_/best-read-it-later-apps',
    path: '/articles/best-read-it-later-apps',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesBookmarkManagerForDevelopersRoute =
  MarketingArticlesBookmarkManagerForDevelopersRouteImport.update({
    id: '/articles_/bookmark-manager-for-developers',
    path: '/articles/bookmark-manager-for-developers',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesChromeBookmarksBarRoute =
  MarketingArticlesChromeBookmarksBarRouteImport.update({
    id: '/articles_/chrome-bookmarks-bar',
    path: '/articles/chrome-bookmarks-bar',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesExportImportBookmarksRoute =
  MarketingArticlesExportImportBookmarksRouteImport.update({
    id: '/articles_/export-import-bookmarks',
    path: '/articles/export-import-bookmarks',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesHowToOrganizeBookmarksChromeRoute =
  MarketingArticlesHowToOrganizeBookmarksChromeRouteImport.update({
    id: '/articles_/how-to-organize-bookmarks-chrome',
    path: '/articles/how-to-organize-bookmarks-chrome',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesHowToOrganizeTooManyOpenTabsRoute =
  MarketingArticlesHowToOrganizeTooManyOpenTabsRouteImport.update({
    id: '/articles_/how-to-organize-too-many-open-tabs',
    path: '/articles/how-to-organize-too-many-open-tabs',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesReadLaterAppChromeIphoneRoute =
  MarketingArticlesReadLaterAppChromeIphoneRouteImport.update({
    id: '/articles_/read-later-app-chrome-iphone',
    path: '/articles/read-later-app-chrome-iphone',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesSafariReadingListRoute =
  MarketingArticlesSafariReadingListRouteImport.update({
    id: '/articles_/safari-reading-list',
    path: '/articles/safari-reading-list',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesSaveLinksWithRaycastRoute =
  MarketingArticlesSaveLinksWithRaycastRouteImport.update({
    id: '/articles_/save-links-with-raycast',
    path: '/articles/save-links-with-raycast',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingArticlesWhereAreMyBookmarksRoute =
  MarketingArticlesWhereAreMyBookmarksRouteImport.update({
    id: '/articles_/where-are-my-bookmarks',
    path: '/articles/where-are-my-bookmarks',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingUHandleRoute = MarketingUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => MarketingRoute,
} as any)
const AppLibraryFoldersFolderIdRoute =
  AppLibraryFoldersFolderIdRouteImport.update({
    id: '/library_/folders/$folderId',
    path: '/library/folders/$folderId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/connect': typeof AppConnectRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof MarketingAboutRoute
  '/articles': typeof MarketingArticlesRoute
  '/chrome-extension': typeof MarketingChromeExtensionRoute
  '/contact': typeof MarketingContactRoute
  '/ios-app': typeof MarketingIosAppRoute
  '/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/raycast': typeof MarketingRaycastRoute
  '/safari-bookmark-manager': typeof MarketingSafariBookmarkManagerRoute
  '/support': typeof MarketingSupportRoute
  '/web-companion': typeof MarketingWebCompanionRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/articles/best-bookmark-manager-chrome': typeof MarketingArticlesBestBookmarkManagerChromeRoute
  '/articles/best-read-it-later-apps': typeof MarketingArticlesBestReadItLaterAppsRoute
  '/articles/bookmark-manager-for-developers': typeof MarketingArticlesBookmarkManagerForDevelopersRoute
  '/articles/chrome-bookmarks-bar': typeof MarketingArticlesChromeBookmarksBarRoute
  '/articles/export-import-bookmarks': typeof MarketingArticlesExportImportBookmarksRoute
  '/articles/how-to-organize-bookmarks-chrome': typeof MarketingArticlesHowToOrganizeBookmarksChromeRoute
  '/articles/how-to-organize-too-many-open-tabs': typeof MarketingArticlesHowToOrganizeTooManyOpenTabsRoute
  '/articles/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/articles/safari-reading-list': typeof MarketingArticlesSafariReadingListRoute
  '/articles/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/articles/where-are-my-bookmarks': typeof MarketingArticlesWhereAreMyBookmarksRoute
  '/u/$handle': typeof MarketingUHandleRoute
  '/library/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof MarketingIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/connect': typeof AppConnectRoute
  '/inbox': typeof AppInboxRoute
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/about': typeof MarketingAboutRoute
  '/articles': typeof MarketingArticlesRoute
  '/chrome-extension': typeof MarketingChromeExtensionRoute
  '/contact': typeof MarketingContactRoute
  '/ios-app': typeof MarketingIosAppRoute
  '/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/raycast': typeof MarketingRaycastRoute
  '/safari-bookmark-manager': typeof MarketingSafariBookmarkManagerRoute
  '/support': typeof MarketingSupportRoute
  '/web-companion': typeof MarketingWebCompanionRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/articles/best-bookmark-manager-chrome': typeof MarketingArticlesBestBookmarkManagerChromeRoute
  '/articles/best-read-it-later-apps': typeof MarketingArticlesBestReadItLaterAppsRoute
  '/articles/bookmark-manager-for-developers': typeof MarketingArticlesBookmarkManagerForDevelopersRoute
  '/articles/chrome-bookmarks-bar': typeof MarketingArticlesChromeBookmarksBarRoute
  '/articles/export-import-bookmarks': typeof MarketingArticlesExportImportBookmarksRoute
  '/articles/how-to-organize-bookmarks-chrome': typeof MarketingArticlesHowToOrganizeBookmarksChromeRoute
  '/articles/how-to-organize-too-many-open-tabs': typeof MarketingArticlesHowToOrganizeTooManyOpenTabsRoute
  '/articles/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/articles/safari-reading-list': typeof MarketingArticlesSafariReadingListRoute
  '/articles/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/articles/where-are-my-bookmarks': typeof MarketingArticlesWhereAreMyBookmarksRoute
  '/u/$handle': typeof MarketingUHandleRoute
  '/library/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/articles': typeof MarketingArticlesRoute
  '/_marketing/chrome-extension': typeof MarketingChromeExtensionRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/ios-app': typeof MarketingIosAppRoute
  '/_marketing/pocket-alternative': typeof MarketingPocketAlternativeRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/raycast': typeof MarketingRaycastRoute
  '/_marketing/safari-bookmark-manager': typeof MarketingSafariBookmarkManagerRoute
  '/_marketing/support': typeof MarketingSupportRoute
  '/_marketing/web-companion': typeof MarketingWebCompanionRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/articles_/best-bookmark-manager-chrome': typeof MarketingArticlesBestBookmarkManagerChromeRoute
  '/_marketing/articles_/best-read-it-later-apps': typeof MarketingArticlesBestReadItLaterAppsRoute
  '/_marketing/articles_/bookmark-manager-for-developers': typeof MarketingArticlesBookmarkManagerForDevelopersRoute
  '/_marketing/articles_/chrome-bookmarks-bar': typeof MarketingArticlesChromeBookmarksBarRoute
  '/_marketing/articles_/export-import-bookmarks': typeof MarketingArticlesExportImportBookmarksRoute
  '/_marketing/articles_/how-to-organize-bookmarks-chrome': typeof MarketingArticlesHowToOrganizeBookmarksChromeRoute
  '/_marketing/articles_/how-to-organize-too-many-open-tabs': typeof MarketingArticlesHowToOrganizeTooManyOpenTabsRoute
  '/_marketing/articles_/read-later-app-chrome-iphone': typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  '/_marketing/articles_/safari-reading-list': typeof MarketingArticlesSafariReadingListRoute
  '/_marketing/articles_/save-links-with-raycast': typeof MarketingArticlesSaveLinksWithRaycastRoute
  '/_marketing/articles_/where-are-my-bookmarks': typeof MarketingArticlesWhereAreMyBookmarksRoute
  '/_marketing/u/$handle': typeof MarketingUHandleRoute
  '/_app/library_/folders/$folderId': typeof AppLibraryFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/sitemap.xml'
    | '/connect'
    | '/inbox'
    | '/library'
    | '/settings'
    | '/about'
    | '/articles'
    | '/chrome-extension'
    | '/contact'
    | '/ios-app'
    | '/pocket-alternative'
    | '/privacy'
    | '/raycast'
    | '/safari-bookmark-manager'
    | '/support'
    | '/web-companion'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/oauth/consent'
    | '/oauth/login'
    | '/articles/best-bookmark-manager-chrome'
    | '/articles/best-read-it-later-apps'
    | '/articles/bookmark-manager-for-developers'
    | '/articles/chrome-bookmarks-bar'
    | '/articles/export-import-bookmarks'
    | '/articles/how-to-organize-bookmarks-chrome'
    | '/articles/how-to-organize-too-many-open-tabs'
    | '/articles/read-later-app-chrome-iphone'
    | '/articles/safari-reading-list'
    | '/articles/save-links-with-raycast'
    | '/articles/where-are-my-bookmarks'
    | '/u/$handle'
    | '/library/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/sitemap.xml'
    | '/connect'
    | '/inbox'
    | '/library'
    | '/settings'
    | '/about'
    | '/articles'
    | '/chrome-extension'
    | '/contact'
    | '/ios-app'
    | '/pocket-alternative'
    | '/privacy'
    | '/raycast'
    | '/safari-bookmark-manager'
    | '/support'
    | '/web-companion'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/oauth/consent'
    | '/oauth/login'
    | '/articles/best-bookmark-manager-chrome'
    | '/articles/best-read-it-later-apps'
    | '/articles/bookmark-manager-for-developers'
    | '/articles/chrome-bookmarks-bar'
    | '/articles/export-import-bookmarks'
    | '/articles/how-to-organize-bookmarks-chrome'
    | '/articles/how-to-organize-too-many-open-tabs'
    | '/articles/read-later-app-chrome-iphone'
    | '/articles/safari-reading-list'
    | '/articles/save-links-with-raycast'
    | '/articles/where-are-my-bookmarks'
    | '/u/$handle'
    | '/library/folders/$folderId'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_marketing'
    | '/sitemap.xml'
    | '/_app/connect'
    | '/_app/inbox'
    | '/_app/library'
    | '/_app/settings'
    | '/_marketing/about'
    | '/_marketing/articles'
    | '/_marketing/chrome-extension'
    | '/_marketing/contact'
    | '/_marketing/ios-app'
    | '/_marketing/pocket-alternative'
    | '/_marketing/privacy'
    | '/_marketing/raycast'
    | '/_marketing/safari-bookmark-manager'
    | '/_marketing/support'
    | '/_marketing/web-companion'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/oauth/consent'
    | '/oauth/login'
    | '/_marketing/'
    | '/_marketing/articles_/best-bookmark-manager-chrome'
    | '/_marketing/articles_/best-read-it-later-apps'
    | '/_marketing/articles_/bookmark-manager-for-developers'
    | '/_marketing/articles_/chrome-bookmarks-bar'
    | '/_marketing/articles_/export-import-bookmarks'
    | '/_marketing/articles_/how-to-organize-bookmarks-chrome'
    | '/_marketing/articles_/how-to-organize-too-many-open-tabs'
    | '/_marketing/articles_/read-later-app-chrome-iphone'
    | '/_marketing/articles_/safari-reading-list'
    | '/_marketing/articles_/save-links-with-raycast'
    | '/_marketing/articles_/where-are-my-bookmarks'
    | '/_marketing/u/$handle'
    | '/_app/library_/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthLoginRoute: typeof OauthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles': {
      id: '/_marketing/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof MarketingArticlesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/chrome-extension': {
      id: '/_marketing/chrome-extension'
      path: '/chrome-extension'
      fullPath: '/chrome-extension'
      preLoaderRoute: typeof MarketingChromeExtensionRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/ios-app': {
      id: '/_marketing/ios-app'
      path: '/ios-app'
      fullPath: '/ios-app'
      preLoaderRoute: typeof MarketingIosAppRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pocket-alternative': {
      id: '/_marketing/pocket-alternative'
      path: '/pocket-alternative'
      fullPath: '/pocket-alternative'
      preLoaderRoute: typeof MarketingPocketAlternativeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/raycast': {
      id: '/_marketing/raycast'
      path: '/raycast'
      fullPath: '/raycast'
      preLoaderRoute: typeof MarketingRaycastRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/safari-bookmark-manager': {
      id: '/_marketing/safari-bookmark-manager'
      path: '/safari-bookmark-manager'
      fullPath: '/safari-bookmark-manager'
      preLoaderRoute: typeof MarketingSafariBookmarkManagerRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/support': {
      id: '/_marketing/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MarketingSupportRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/web-companion': {
      id: '/_marketing/web-companion'
      path: '/web-companion'
      fullPath: '/web-companion'
      preLoaderRoute: typeof MarketingWebCompanionRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/articles_/best-bookmark-manager-chrome': {
      id: '/_marketing/articles_/best-bookmark-manager-chrome'
      path: '/articles/best-bookmark-manager-chrome'
      fullPath: '/articles/best-bookmark-manager-chrome'
      preLoaderRoute: typeof MarketingArticlesBestBookmarkManagerChromeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/best-read-it-later-apps': {
      id: '/_marketing/articles_/best-read-it-later-apps'
      path: '/articles/best-read-it-later-apps'
      fullPath: '/articles/best-read-it-later-apps'
      preLoaderRoute: typeof MarketingArticlesBestReadItLaterAppsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/bookmark-manager-for-developers': {
      id: '/_marketing/articles_/bookmark-manager-for-developers'
      path: '/articles/bookmark-manager-for-developers'
      fullPath: '/articles/bookmark-manager-for-developers'
      preLoaderRoute: typeof MarketingArticlesBookmarkManagerForDevelopersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/chrome-bookmarks-bar': {
      id: '/_marketing/articles_/chrome-bookmarks-bar'
      path: '/articles/chrome-bookmarks-bar'
      fullPath: '/articles/chrome-bookmarks-bar'
      preLoaderRoute: typeof MarketingArticlesChromeBookmarksBarRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/export-import-bookmarks': {
      id: '/_marketing/articles_/export-import-bookmarks'
      path: '/articles/export-import-bookmarks'
      fullPath: '/articles/export-import-bookmarks'
      preLoaderRoute: typeof MarketingArticlesExportImportBookmarksRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/how-to-organize-bookmarks-chrome': {
      id: '/_marketing/articles_/how-to-organize-bookmarks-chrome'
      path: '/articles/how-to-organize-bookmarks-chrome'
      fullPath: '/articles/how-to-organize-bookmarks-chrome'
      preLoaderRoute: typeof MarketingArticlesHowToOrganizeBookmarksChromeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/how-to-organize-too-many-open-tabs': {
      id: '/_marketing/articles_/how-to-organize-too-many-open-tabs'
      path: '/articles/how-to-organize-too-many-open-tabs'
      fullPath: '/articles/how-to-organize-too-many-open-tabs'
      preLoaderRoute: typeof MarketingArticlesHowToOrganizeTooManyOpenTabsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/read-later-app-chrome-iphone': {
      id: '/_marketing/articles_/read-later-app-chrome-iphone'
      path: '/articles/read-later-app-chrome-iphone'
      fullPath: '/articles/read-later-app-chrome-iphone'
      preLoaderRoute: typeof MarketingArticlesReadLaterAppChromeIphoneRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/safari-reading-list': {
      id: '/_marketing/articles_/safari-reading-list'
      path: '/articles/safari-reading-list'
      fullPath: '/articles/safari-reading-list'
      preLoaderRoute: typeof MarketingArticlesSafariReadingListRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/save-links-with-raycast': {
      id: '/_marketing/articles_/save-links-with-raycast'
      path: '/articles/save-links-with-raycast'
      fullPath: '/articles/save-links-with-raycast'
      preLoaderRoute: typeof MarketingArticlesSaveLinksWithRaycastRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/articles_/where-are-my-bookmarks': {
      id: '/_marketing/articles_/where-are-my-bookmarks'
      path: '/articles/where-are-my-bookmarks'
      fullPath: '/articles/where-are-my-bookmarks'
      preLoaderRoute: typeof MarketingArticlesWhereAreMyBookmarksRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/u/$handle': {
      id: '/_marketing/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof MarketingUHandleRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/library_/folders/$folderId': {
      id: '/_app/library_/folders/$folderId'
      path: '/library/folders/$folderId'
      fullPath: '/library/folders/$folderId'
      preLoaderRoute: typeof AppLibraryFoldersFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppLibraryFoldersFolderIdRoute: typeof AppLibraryFoldersFolderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppInboxRoute: AppInboxRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppLibraryFoldersFolderIdRoute: AppLibraryFoldersFolderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingArticlesRoute: typeof MarketingArticlesRoute
  MarketingChromeExtensionRoute: typeof MarketingChromeExtensionRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingIosAppRoute: typeof MarketingIosAppRoute
  MarketingPocketAlternativeRoute: typeof MarketingPocketAlternativeRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingRaycastRoute: typeof MarketingRaycastRoute
  MarketingSafariBookmarkManagerRoute: typeof MarketingSafariBookmarkManagerRoute
  MarketingSupportRoute: typeof MarketingSupportRoute
  MarketingWebCompanionRoute: typeof MarketingWebCompanionRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingArticlesBestBookmarkManagerChromeRoute: typeof MarketingArticlesBestBookmarkManagerChromeRoute
  MarketingArticlesBestReadItLaterAppsRoute: typeof MarketingArticlesBestReadItLaterAppsRoute
  MarketingArticlesBookmarkManagerForDevelopersRoute: typeof MarketingArticlesBookmarkManagerForDevelopersRoute
  MarketingArticlesChromeBookmarksBarRoute: typeof MarketingArticlesChromeBookmarksBarRoute
  MarketingArticlesExportImportBookmarksRoute: typeof MarketingArticlesExportImportBookmarksRoute
  MarketingArticlesHowToOrganizeBookmarksChromeRoute: typeof MarketingArticlesHowToOrganizeBookmarksChromeRoute
  MarketingArticlesHowToOrganizeTooManyOpenTabsRoute: typeof MarketingArticlesHowToOrganizeTooManyOpenTabsRoute
  MarketingArticlesReadLaterAppChromeIphoneRoute: typeof MarketingArticlesReadLaterAppChromeIphoneRoute
  MarketingArticlesSafariReadingListRoute: typeof MarketingArticlesSafariReadingListRoute
  MarketingArticlesSaveLinksWithRaycastRoute: typeof MarketingArticlesSaveLinksWithRaycastRoute
  MarketingArticlesWhereAreMyBookmarksRoute: typeof MarketingArticlesWhereAreMyBookmarksRoute
  MarketingUHandleRoute: typeof MarketingUHandleRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingArticlesRoute: MarketingArticlesRoute,
  MarketingChromeExtensionRoute: MarketingChromeExtensionRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingIosAppRoute: MarketingIosAppRoute,
  MarketingPocketAlternativeRoute: MarketingPocketAlternativeRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingRaycastRoute: MarketingRaycastRoute,
  MarketingSafariBookmarkManagerRoute: MarketingSafariBookmarkManagerRoute,
  MarketingSupportRoute: MarketingSupportRoute,
  MarketingWebCompanionRoute: MarketingWebCompanionRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingArticlesBestBookmarkManagerChromeRoute:
    MarketingArticlesBestBookmarkManagerChromeRoute,
  MarketingArticlesBestReadItLaterAppsRoute:
    MarketingArticlesBestReadItLaterAppsRoute,
  MarketingArticlesBookmarkManagerForDevelopersRoute:
    MarketingArticlesBookmarkManagerForDevelopersRoute,
  MarketingArticlesChromeBookmarksBarRoute:
    MarketingArticlesChromeBookmarksBarRoute,
  MarketingArticlesExportImportBookmarksRoute:
    MarketingArticlesExportImportBookmarksRoute,
  MarketingArticlesHowToOrganizeBookmarksChromeRoute:
    MarketingArticlesHowToOrganizeBookmarksChromeRoute,
  MarketingArticlesHowToOrganizeTooManyOpenTabsRoute:
    MarketingArticlesHowToOrganizeTooManyOpenTabsRoute,
  MarketingArticlesReadLaterAppChromeIphoneRoute:
    MarketingArticlesReadLaterAppChromeIphoneRoute,
  MarketingArticlesSafariReadingListRoute:
    MarketingArticlesSafariReadingListRoute,
  MarketingArticlesSaveLinksWithRaycastRoute:
    MarketingArticlesSaveLinksWithRaycastRoute,
  MarketingArticlesWhereAreMyBookmarksRoute:
    MarketingArticlesWhereAreMyBookmarksRoute,
  MarketingUHandleRoute: MarketingUHandleRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthLoginRoute: OauthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
